### ISSUE TITLE
ValField breaks in Django Model of WorkflowActionSet

### ISSUE THREAD

**Issue by miketynes** [darkreactions/ESCALATE#59]
The current model of `WorkflowActionSet` is non-functional. 

It is broken in this line:
https://github.com/darkreactions/ESCALATE/blob/ff88f1ca5b3cf8f5a3df18de5ca113a30fd7fd2e/escalate/core/models/view_tables/workflow.py#L671

Which gives an IndexError in `ValField.from_db` (this line): 
https://github.com/darkreactions/ESCALATE/blob/ff88f1ca5b3cf8f5a3df18de5ca113a30fd7fd2e/escalate/core/models/custom_types.py#L52

(Full Traceback below) 

N.B.: I encountered this issue by adding `WorkflowActionSet` to the `core_views` set and accessing the API endpoint. 
My db was populated with the mojito workflow which you can generate by running `data_model/sql_core/dev_cocktail.sql` (I am unsure if this issue appears with the workflows that are in the DB before running this script -- it might) 

Full traceback: 

```

Traceback (most recent call last):
  File "/home/mike/miniconda3/envs/escalate-3.8.3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mike/miniconda3/envs/escalate-3.8.3/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mike/miniconda3/envs/escalate-3.8.3/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mike/miniconda3/envs/escalate-3.8.3/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mike/miniconda3/envs/escalate-3.8.3/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mike/miniconda3/envs/escalate-3.8.3/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mike/miniconda3/envs/escalate-3.8.3/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mike/miniconda3/envs/escalate-3.8.3/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mike/miniconda3/envs/escalate-3.8.3/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mike/miniconda3/envs/escalate-3.8.3/lib/python3.8/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/home/mike/miniconda3/envs/escalate-3.8.3/lib/python3.8/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/home/mike/miniconda3/envs/escalate-3.8.3/lib/python3.8/site-packages/rest_framework/pagination.py", line 391, in paginate_queryset
    return list(queryset[self.offset:self.offset + self.limit])
  File "/home/mike/miniconda3/envs/escalate-3.8.3/lib/python3.8/site-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "/home/mike/miniconda3/envs/escalate-3.8.3/lib/python3.8/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/mike/miniconda3/envs/escalate-3.8.3/lib/python3.8/site-packages/django/db/models/query.py", line 74, in __iter__
    for row in compiler.results_iter(results):
  File "/home/mike/miniconda3/envs/escalate-3.8.3/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1096, in apply_converters
    value = converter(value, expression, connection)
  File "/home/mike/miniconda3/envs/escalate-3.8.3/lib/python3.8/site-packages/django/contrib/postgres/fields/array.py", line 117, in _from_db_value
    return [
  File "/home/mike/miniconda3/envs/escalate-3.8.3/lib/python3.8/site-packages/django/contrib/postgres/fields/array.py", line 118, in <listcomp>
    self.base_field.from_db_value(item, expression, connection)
  File "/mnt/c/Users/Public/repos/ESCALATE/escalate/core/models/custom_types.py", line 111, in from_db_value
    return Val.from_db(value)
  File "/mnt/c/Users/Public/repos/ESCALATE/escalate/core/models/custom_types.py", line 52, in from_db
    type_uuid = args[0]

Exception Type: IndexError at /api/workflowactionset/
Exception Value: list index out of range
```

**Comment by vshekar** [comment]
Read works with commit 150285755947daf2425d236902e8e495dc256767. Post needs testing. @miketynes please test post if you get a chance! Thanks

**Comment by miketynes** [comment]
fixed a while ago
